# 使用Selenium官方带有Chrome和ChromeDriver的基础镜像
FROM selenium/standalone-chrome:latest
# 设置工作目录
WORKDIR /app
# # 复制requirements.txt到工作目录
# COPY requirements.txt .
# # 安装Python依赖
# RUN pip install --no-cache-dir -r requirements.txt
